language: objective-c
before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
script: xctool -workspace UICustomizeKit.xcworkspace -scheme UICustomizeKit -sdk iphonesimulator -configuration Release test -test-sdk iphonesimulator